### ISSUE TITLE
How to upgrade cilium

### ISSUE THREAD

**Issue by hollden** [isovalent/cilium-olm#20]
Good day!
I have installed Cilium on OKD4.12 Cluster by doc here https://docs.cilium.io/en/v1.11/gettingstarted/k8s-install-openshift-okd/
Now I want to upgrade Cilium version, and it is not clear for me how I have do to it properly.
My only assumption that I should apply all manifests from folder manifests (preliminarily choose version).
Can you provide some instruction or tell about the upgrade process on OKD4 in more detail?

Thank you in advance!

**Comment by liyihuang** [comment]
I just worked on this last week. I guess you are running into the issue that you are not able to perform the patch and minor upgrade through the openshift GUI through operator hub. if that's the case, please delete the csv CRD from your cluster. then you will be to receive the update from the operator hub

**Comment by albionb96** [comment]
@liyihuang that one is not working. Do we have any other method to upgrade Cilium on Openshift other than, re-deploying the whole cluster with new manifest files?

**Comment by liyihuang** [comment]
I did write some docs for the enterprise version a few months back. Let me see if I can convert it to the OSS one. 

The TLDR is

```If you manually applied the clusterserviceversion during the installation, you must remove the CR first. Otherwise, your upgrade will fail.```

Then you can just follow a normal OCP operator process following this doc (https://docs.openshift.com/container-platform/4.10/operators/admin/olm-upgrading-operators.html)

**Comment by albionb96** [comment]
@liyihuang the CSV CRD in my case had no entry regarding Cilium, it was all about other stuff in openshift. What I did it I deleted the operator and the subscription and then upgraded the cilium with cli: cilium upgrade -n cilium, and then it worked.

I had another question which I posted here: https://github.com/isovalent/olm-for-cilium/issues/30, is there any other way to install cilium on openshift, except the documented way. Is it possible to install it with helm charts on openshift?

**Comment by liyihuang** [comment]
I dont think using the cilium CLI is the proper way to upgrade the cilium in the OCP environment. I have only tested the cilium following the OCP operator lifecycle... cilium upgrade command will only render the manifest and replace those which is not enough for OCP as far as I know

To your 2nd question, it's possible but there are more steps you might need to perform(I only heard that internally but didn't try it), and the best way to install Cilium in OCP environment is still through OCP bootstrap.

**Comment by camrossi** [comment]
I am also a bit lost on this... I installed Cilium as per the instructions i.e. GitClone and copy the manifests into the Openshit installation folder. 

So far so good I can login to my cluster that came up perfectly fine and I can see the Operator
<img width="1372" alt="image" src="https://github.com/isovalent/olm-for-cilium/assets/16535101/764a04a7-4b71-4f0d-9afb-6e006da73ca4">

But there as no subscriptions for it:
<img width="908" alt="image" src="https://github.com/isovalent/olm-for-cilium/assets/16535101/52c0bdc1-15da-483e-925e-ec0216b62bc7">


So how am I supposed to upgrade Cilium now? Also I can see that I can re-install the operator as well:
<img width="417" alt="image" src="https://github.com/isovalent/olm-for-cilium/assets/16535101/7958f4e9-5ac4-47a3-99ce-e2e841f5b779">


Do I need to delete the Operator and Install it from the OperatorHub? 

The documentation is really lacking here.

**Comment by liyihuang** [comment]
please read https://github.com/isovalent/olm-for-cilium/issues/20#issuecomment-1779088831 @camrossi

**Comment by camrossi** [comment]
> please read [#20 (comment)](https://github.com/isovalent/olm-for-cilium/issues/20#issuecomment-1779088831) @camrossi

I did read it and perhaps due to my lack of knowledge tells me absolutely nothing... Are you saying we need to delete the Operator? 
<img width="1433" alt="image" src="https://github.com/isovalent/olm-for-cilium/assets/16535101/9b8ccd43-533d-4c4f-a826-6aab47192b49">
and then re-install it ? 

Any impacts on the workload on this cluster?

This should be really documented the lack of doc dosen't really gives me much confidence about running this in production.

**Comment by chancez** [comment]
@camrossi you need to follow https://docs.openshift.com/container-platform/4.10/operators/admin/olm-upgrading-operators.html to do upgrades. If you hit issues; you may need to do [this](https://github.com/isovalent/olm-for-cilium/issues/20#issuecomment-1779088831):
> If you manually applied the clusterserviceversion during the installation, you must remove the CR first. Otherwise, your upgrade will fail.

If you not seeing subscriptions; you may have missed a step, since it should be in the bundle: https://github.com/isovalent/olm-for-cilium/blob/main/manifests/cilium.v1.15.1/cluster-network-06-cilium-00013-cilium-subscription.yaml

**Comment by camrossi** [comment]
@chancez that might be the core of the problem, I do not have any subscriptions... as show in my screenshots but that file is present in my manifest folder as well as in the cluster so indeed is the CSV thing. 

```
oc -n cilium describe Subscription

Status:
    Message:               constraints not satisfiable: clusterserviceversion cilium.v1.15.1-x7095b76 exists and is not referenced by a subscription, @existing/cilium//cilium.v1.15.1-x7095b76 and certified-operators/openshift-marketplace/1.15/cilium.v1.15.1-x7095b76 provide CiliumConfig (cilium.io/v1alpha1), subscription cilium requires certified-operators/openshift-marketplace/1.15/cilium.v1.15.1-x7095b76, subscription cilium exists
```

I did this:
`oc -n cilium delete clusterserviceversion cilium.v1.15.1-x7095b76`

Now the Operator asked me to install itself again:
<img width="1418" alt="image" src="https://github.com/isovalent/olm-for-cilium/assets/16535101/5f3345d8-828d-45c7-ab3b-d4a8e4969eac">

I accepted this And is working fine.
Thanks for pointing me in the right direction.

**Comment by liyihuang** [comment]
Do you see anything when you run `oc get csv -n cilium`?

**Comment by camrossi** [comment]
@liyihuang I had indeed a clusterserviceversion I deleted it and accepted the InstallPlan and now I have a new csv:

oc -n cilium get csv
NAME                      DISPLAY   VERSION           REPLACES   PHASE
cilium.v1.15.1-x7095b76   Cilium    1.15.1+x7095b76              Succeeded
This got re-added after I deleted the original one. 

Side topic how often is the operator updated? We are already at Cilium 1.5.3, 1.5.1. was released back in Feb.

**Comment by liyihuang** [comment]
patch should be every month unless there is some issues.

**Comment by camrossi** [comment]
@liyihuang I see this is closed but I don't think this has been documented anywhere that I can see?

**Comment by liyihuang** [comment]
@camrossi issue has been tracked by https://github.com/isovalent/olm-for-cilium/issues/25 where you shouldn't manually delete the CSV based on my understanding. that's why I closed this one

**Comment by camrossi** [comment]
Thank you @liyihuang makes sense !
